### ISSUE TITLE
Switched Author/Image Name

### ISSUE THREAD

**Issue by schwartzadev** [ercsoftware11/wallpaperimages#1]
wallpapers.json:664

> "author": "Samsung 3",

**Comment by ercsoftware11** [comment]
Hey man! What seems to be the issue?

**Comment by schwartzadev** [comment]
I was looking through all of the names and formatting in Polar Dashboard and I noticed that in the wallpapers.json file, on line 664, the author of the wallpaper is "Samsung 3" while the name of the wallpaper is "Samsung." I do believe that these should be the other way around...

Awesome work so far!
